/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedProofRouteImport } from './routes/_authenticated/proof'
import { Route as AuthenticatedProductRouteImport } from './routes/_authenticated/product'
import { Route as AuthenticatedPilotsRouteImport } from './routes/_authenticated/pilots'
import { Route as AuthenticatedMilestonesRouteImport } from './routes/_authenticated/milestones'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDataEntryRouteImport } from './routes/_authenticated/data-entry'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProofRoute = AuthenticatedProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductRoute = AuthenticatedProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotsRoute = AuthenticatedPilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMilestonesRoute = AuthenticatedMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataEntryRoute = AuthenticatedDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/data-entry': typeof AuthenticatedDataEntryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/members': typeof AuthenticatedMembersRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/pilots': typeof AuthenticatedPilotsRoute
  '/product': typeof AuthenticatedProductRoute
  '/proof': typeof AuthenticatedProofRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/data-entry': typeof AuthenticatedDataEntryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/members': typeof AuthenticatedMembersRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/pilots': typeof AuthenticatedPilotsRoute
  '/product': typeof AuthenticatedProductRoute
  '/proof': typeof AuthenticatedProofRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/data-entry': typeof AuthenticatedDataEntryRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/milestones': typeof AuthenticatedMilestonesRoute
  '/_authenticated/pilots': typeof AuthenticatedPilotsRoute
  '/_authenticated/product': typeof AuthenticatedProductRoute
  '/_authenticated/proof': typeof AuthenticatedProofRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/content'
    | '/copilot'
    | '/crm'
    | '/data-entry'
    | '/documents'
    | '/history'
    | '/investor'
    | '/members'
    | '/milestones'
    | '/pilots'
    | '/product'
    | '/proof'
    | '/tasks'
    | '/team'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/applications'
    | '/content'
    | '/copilot'
    | '/crm'
    | '/data-entry'
    | '/documents'
    | '/history'
    | '/investor'
    | '/members'
    | '/milestones'
    | '/pilots'
    | '/product'
    | '/proof'
    | '/tasks'
    | '/team'
    | '/api/chat'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/content'
    | '/_authenticated/copilot'
    | '/_authenticated/crm'
    | '/_authenticated/data-entry'
    | '/_authenticated/documents'
    | '/_authenticated/history'
    | '/_authenticated/investor'
    | '/_authenticated/members'
    | '/_authenticated/milestones'
    | '/_authenticated/pilots'
    | '/_authenticated/product'
    | '/_authenticated/proof'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/api/chat'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proof': {
      id: '/_authenticated/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof AuthenticatedProofRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product': {
      id: '/_authenticated/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthenticatedProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilots': {
      id: '/_authenticated/pilots'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof AuthenticatedPilotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milestones': {
      id: '/_authenticated/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof AuthenticatedMilestonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-entry': {
      id: '/_authenticated/data-entry'
      path: '/data-entry'
      fullPath: '/data-entry'
      preLoaderRoute: typeof AuthenticatedDataEntryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDataEntryRoute: typeof AuthenticatedDataEntryRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMilestonesRoute: typeof AuthenticatedMilestonesRoute
  AuthenticatedPilotsRoute: typeof AuthenticatedPilotsRoute
  AuthenticatedProductRoute: typeof AuthenticatedProductRoute
  AuthenticatedProofRoute: typeof AuthenticatedProofRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDataEntryRoute: AuthenticatedDataEntryRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMilestonesRoute: AuthenticatedMilestonesRoute,
  AuthenticatedPilotsRoute: AuthenticatedPilotsRoute,
  AuthenticatedProductRoute: AuthenticatedProductRoute,
  AuthenticatedProofRoute: AuthenticatedProofRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
